const fs = require('fs');

const WEAPON_NAME_MAP = {
    'BEHR_LASERCANNON_S1': 'M3A Laser Cannon',
    'BEHR_LASERCANNON_S2': 'M4A Laser Cannon',
    'BEHR_LASERCANNON_S3': 'M5A Laser Cannon',
    'BEHR_LASERCANNON_S4': 'M6A Laser Cannon',
    'BEHR_LASERCANNON_S5': 'M7A Laser Cannon',
    'BEHR_LASERCANNON_S6': 'M8A Laser Cannon',
    'BEHR_LASERREPEATER_S1': 'M3A Laser Repeater',
    'BEHR_LASERREPEATER_S2': 'M4A Laser Repeater',
    'BEHR_LASERREPEATER_S3': 'M5A Laser Repeater',
    'KLWE_LASERREPEATER_S1': 'Bulldog Repeater',
    'KLWE_LASERREPEATER_S2': 'Badger Repeater',
    'KLWE_LASERREPEATER_S3': 'Panther Repeater',
    'KLWE_LASERREPEATER_S4': 'Rhino Repeater',
    'KLWE_LASERREPEATER_S5': 'Galdereen Repeater',
    'KLWE_LASERREPEATER_S6': 'Mammoth Repeater',
    'BEHR_BALLISTICGATLING_S4': 'AD4B Gatling',
    'BEHR_BALLISTICGATLING_S5': 'AD5B Gatling',
    'BEHR_BALLISTICGATLING_S6': 'AD6B Gatling'
};

const COMPONENT_NAME_MAP = {
    // Shields
    'SHLD_BEHR_S01_6SA': 'Arbiter',
    'SHLD_BEHR_S02_5MA': 'Chimalli',
    'SHLD_BEHR_S03_7CA': 'Nargun',
    'SHLD_BEHR_S01_7SA': 'Concord',
    'SHLD_BEHR_S02_6MA': 'Kozane',
    'SHLD_BEHR_S03_6CA': 'Bila',
    'SHLD_BEHR_S01_5SA': 'Rhada',
    'SHLD_BEHR_S02_7MA': 'Lorica',
    'SHLD_BEHR_S03_5CA': 'Akura',
    'SHLD_ASAS_S01_MIRAGE': 'Mirage',
    'SHLD_ASAS_S01_VEIL': 'Veil',
    'SHLD_ASAS_S01_CLOAK': 'Cloak',
    'SHLD_ASAS_S01_SHIMMER': 'Shimmer',
    'SHLD_ASAS_S02_SHROUD': 'Shroud',
    'SHLD_ASAS_S02_UMBRA': 'Umbra',
    'SHLD_ASAS_S02_SHEUT': 'Sheut',
    'SHLD_ASAS_S02_OBSCURA': 'Obscura',
    'SHLD_BASL_S00_CASTRA': 'Castra',
    'SHLD_BASL_S01_STEWARD': 'Steward',
    'SHLD_BASL_S02_ASPIS': 'Aspis',
    'SHLD_BASL_S03_WARD': 'Ward',
    'SHLD_BASL_S01_PALISADE': 'Palisade',
    'SHLD_BASL_S01_GUARDIAN': 'Guardian',
    'SHLD_BASL_S01_BULWARK': 'Bulwark',
    'SHLD_BASL_S02_ARMADA': 'Armada',
    'SHLD_BASL_S02_RAMPART': 'Rampart',
    'SHLD_BASL_S02_CITADEL': 'Citadel',
    'SHLD_BASL_S03_PARAPET': 'Parapet',
    'SHLD_BASL_S03_STRONGHOLD': 'Stronghold',
    'SHLD_BASL_S03_BARBICAN': 'Barbican',
    'SHLD_GODI_S01_FR66': 'FR-66',
    'SHLD_GODI_S02_FR76': 'FR-76',
    'SHLD_GODI_S03_FR86': 'FR-86',
    'SHLD_GODI_S01_ALLSTOP': 'AllStop',
    'SHLD_GODI_S01_FORCEWALL': 'ForceWall',
    'SHLD_GODI_S01_SECUREHYDE': 'SecureHyde',
    'SHLD_GODI_S02_SECURESHIELD': 'SecureShield',
    'SHLD_GODI_S02_COVERALL': 'CoverAll',
    'SHLD_GODI_S02_FULLSTOP': 'FullStop',
    'SHLD_GODI_S03_SURESTOP': 'SureStop',
    'SHLD_GODI_S03_FULLBLOCK': 'FullBlock',
    'SHLD_GODI_S03_SECURESCREEN': 'SecureScreen',
    'SHLD_BANU_S01_PLACEHOLDER': 'Suldrath',
    'SHLD_BANU_S02_PLACEHOLDER': 'Sukoran',
    'SHLD_YORM_S01_FALCO': 'Falco',
    'SHLD_YORM_S01_JAGHTE': 'Jaghte',
    'SHLD_YORM_S01_TARGA': 'Targa',
    'SHLD_YORM_S02_BAMOTY': 'Bamoty',
    'SHLD_YORM_S02_TRENTA': 'Trenta',
    'SHLD_YORM_S02_HALTUR': 'Haltur',
    'SHLD_SECO_S00_PIN': 'Pin',
    'SHLD_SECO_S01_HEX': 'Hex',
    'SHLD_SECO_S01_INK': 'Ink',
    'SHLD_SECO_S01_WEB': 'Web',
    'SHLD_SECO_S02_RPEL': 'Rpel',
    'SHLD_SECO_S02_STOP': 'Stop',
    'SHLD_SECO_S02_BLOC': 'Bloc',
    'SHLD_SECO_S03_GUARD': 'Guard',
    'SHLD_SECO_S03_ARMOR': 'Armor',
    'SHLD_SECO_S03_HAVEN': 'Haven',
    'SHLD_AEGS_S04_RECLAIMER': 'RS-Barrier',
    'SHLD_GODI_S04_IDRIS': 'Holdstrong',
    'SHLD_RSI_S04_POLARIS': 'Glacis',
    'SHLD_ORIG_S04_890J': 'Glacis',

    // Power Plants
    'POWR_ACOM_S01_SUNFLARE': 'SunFlare',
    'POWR_ACOM_S01_STARHEART': 'StarHeart',
    'POWR_ACOM_S02_SOLARFLARE': 'SolarFlare',
    'POWR_ACOM_S02_STARBURN': 'StarBurn',
    'POWR_ACOM_S02_LUXCORE': 'LuxCore',
    'POWR_ACOM_S01_LUMACORE': 'LumaCore',
    'POWR_AEGS_S03_FULGUR': 'Fulgur',
    'POWR_AEGS_S03_DRASSIK': 'Drassik',
    'POWR_AEGS_S01_QUADRACELL': 'QuadraCell',
    'POWR_AEGS_S02_QUADRACELLMT': 'QuadraCell MT',
    'POWR_AEGS_S03_QUADRACELLMX': 'QuadraCell MX',
    'POWR_AEGS_S02_BOLIDE': 'Bolide',
    'POWR_AEGS_S03_CENTURION': 'Centurion',
    'POWR_AEGS_S01_REGULUS': 'Regulus',
    'POWR_AEGS_S01_CHARGER': 'Charger',
    'POWR_AEGS_S02_MAELSTROM': 'Maelstrom',
    'POWR_AEGS_S02_VORTEX': 'Vortex',
    'POWR_AEGS_S01_FIERELLCASCADE': 'Fierell Cascade',
    'POWR_AMRS_S01_OVERDRIVE': 'OverDrive',
    'POWR_AMRS_S02_JS400': 'JS-400',
    'POWR_AMRS_S02_ULTRAFLUX': 'UltraFlux',
    'POWR_AMRS_S03_SUPERDRIVE': 'SuperDrive',
    'POWR_AMRS_S02_EXOGEN': 'ExoGen',
    'POWR_AMRS_S01_HYPERGEN': 'HyperGen',
    'POWR_AMRS_S03_JS500': 'JS-500',
    'POWR_AMRS_S02_TURBODRIVE': 'TurboDrive',
    'POWR_AMRS_S01_DYNAFLUX': 'DynaFlux',
    'POWR_AMRS_S03_SMARTGEN': 'SmartGen',
    'POWR_AMRS_S01_JS300': 'JS-300',
    'POWR_AMRS_S03_MEGAFLUX': 'MegaFlux',
    'POWR_JUST_S01_FORTITUDE': 'Fortitude',
    'POWR_JUST_S03_DURANGO': 'Durango',
    'POWR_JUST_S01_ENDURANCE': 'Endurance',
    'POWR_JUST_S00_DEFIANT': 'Defiant',
    'POWR_JUST_S02_DILIGENCE': 'Diligence',
    'POWR_JUST_S02_GENOA': 'Genoa',
    'POWR_JUST_S02_TROMMEL': 'Trommel',
    'POWR_JUST_S03_GINZEL': 'Ginzel',
    'POWR_JUST_S02_SEDULITY': 'Sedulity',
    'POWR_JUST_S00_STEADFAST': 'Steadfast',
    'POWR_JUST_S01_ROUGHNECK': 'Roughneck',
    'POWR_JUST_S03_RELIANCE': 'Reliance',
    'POWR_JUST_S01_BRETON': 'Breton',
    'POWR_JUST_S00_JENNET': 'Jennet',
    'POWR_LPLT_S00_DURAJET': 'DuraJet',
    'POWR_LPLT_S03_IONSURGEPRO': 'IonSurge Pro',
    'POWR_LPLT_S00_RADIX': 'Radix',
    'POWR_LPLT_S03_SPARKJETPRO': 'SparkJet Pro',
    'POWR_LPLT_S01_POWERBOLT': 'PowerBolt',
    'POWR_LPLT_S02_FULLFORCE': 'FullForce',
    'POWR_LPLT_S00_IONWAVE': 'IonWave',
    'POWR_LPLT_S03_FULLFORCEPRO': 'FullForce Pro',
    'POWR_LPLT_S02_SPARKJET': 'SparkJet',
    'POWR_LPLT_S02_IONSURGE': 'IonSurge',
    'POWR_LPLT_S01_IONBURST': 'IonBurst',
    'POWR_LPLT_S01_ZAPJET': 'ZapJet',
    'POWR_SASU_S01_MAGNABLOOM': 'MagnaBloom',
    'POWR_SASU_S01_LIGHTBLOSSOM': 'LightBlossom',
    'POWR_SASU_S03_NEWDAWN': 'NewDawn',
    'POWR_SASU_S03_TIGERLILLY': 'TigerLilly',
    'POWR_SASU_S01_WHITEROSE': 'WhiteRose',
    'POWR_SASU_S02_DAYBREAK': 'DayBreak',
    'POWR_SASU_S02_RADIANCE': 'Radiance',
    'POWR_SASU_S03_CELESTIAL': 'Celestial',
    'POWR_SASU_S02_LOTUS': 'Lotus',
    'POWR_TYDT_S02_CIRRUS': 'Cirrus',
    'POWR_TYDT_S02_ECLIPSE': 'Eclipse',
    'POWR_TYDT_S02_GAMMAMAX': 'GammaMax',
    'POWR_TYDT_S01_SLIPSTREAM': 'Slipstream',
    'POWR_TYDT_S01_SONICLITE': 'SonicLite',
    'POWR_TYDT_S01_DELTAMAX': 'DeltaMax',
    'POWR_RSI_S04_POLARIS': 'Stellate',
    'POWR_ORIG_S04_890J': 'Stellate',

    // Coolers
    'COOL_AEGS_S01_GLACIER': 'Glacier',
    'COOL_AEGS_S02_BOREAL': 'Boreal',
    'COOL_AEGS_S02_ARCTIC': 'Arctic',
    'COOL_AEGS_S01_TUNDRA': 'Tundra',
    'COOL_AEGS_S02_PERMAFROST': 'Permafrost',
    'COOL_AEGS_S03_TEMPEST': 'Tempest',
    'COOL_AEGS_S03_MERCURY': 'Mercury',
    'COOL_AEGS_S03_GALINSTAN': 'Galinstan',
    'COOL_AEGS_S03_BLIZZARD': 'Blizzard',
    'COOL_AEGS_S01_POLAR': 'Polar',
    'COOL_AEGS_S01_BRACER': 'Bracer',
    'COOL_AEGS_S02_AVALANCHE': 'Avalanche',
    'COOL_AEGS_S04_RECLAIMER': 'Algid',
    'COOL_JSPN_S01_WINTERSTAR': 'Winter-Star',
    'COOL_JSPN_S00_FROSTSTARSL': 'Frost-Star SL',
    'COOL_JSPN_S00_WINTERSTARSL': 'Winter-Star SL',
    'COOL_JSPN_S02_FROSTSTAREX': 'Frost-Star EX',
    'COOL_JSPN_S01_CRYOSTAR': 'Cryo-Star',
    'COOL_JSPN_S00_CRYOSTARSL': 'Cryo-Star SL',
    'COOL_JSPN_S01_FROSTSTAR': 'Frost-Star',
    'COOL_JSPN_S02_WINTERSTAREX': 'Winter-Star EX',
    'COOL_JSPN_S03_WINTERSTARXL': 'Winter-Star XL',
    'COOL_JSPN_S02_CRYOSTAREX': 'Cryo-Star EX',
    'COOL_JSPN_S03_FROSTSTARXL': 'Frost-Star XL',
    'COOL_JSPN_S03_CRYOSTARXL': 'Cryo-Star XL',
    'COOL_WCPR_S00_FRIDAN': 'Fridan',
    'COOL_WCPR_S01_BERIAN': 'Berian',
    'COOL_WCPR_S00_KELVID': 'Kelvid',
    'COOL_WCPR_S03_KRAGEN': 'Kragen',
    'COOL_WCPR_S03_DRAUG': 'Draug',
    'COOL_WCPR_S03_ELSEN': 'Elsen',
    'COOL_WCPR_S00_TEPILO': 'Tepilo',
    'COOL_WCPR_S01_GELID': 'Gelid',
    'COOL_WCPR_S02_AUFEIS': 'Aufeis',
    'COOL_WCPR_S02_TAIGA': 'Taiga',
    'COOL_WCPR_S02_GRAUPEL': 'Graupel',
    'COOL_WCPR_S01_ENDO': 'Endo',
    'COOL_JUST_S01_THERMAX': 'Thermax',
    'COOL_JUST_S03_HYDROPULSE': 'Hydropulse',
    'COOL_JUST_S01_HYDROCEL': 'Hydrocel',
    'COOL_JUST_S02_HYDROJET': 'Hydrojet',
    'COOL_JUST_S01_ULTRAFLOW': 'Ultra-Flow',
    'COOL_JUST_S02_SNOWFALL': 'Snowfall',
    'COOL_JUST_S02_SNOWPACK': 'Snowpack',
    'COOL_JUST_S03_CHILLMAX': 'Chill-Max',
    'COOL_JUST_S03_THERMALCORE': 'ThermalCore',
    'COOL_JUST_S02_COOLCORE': 'CoolCore',
    'COOL_JUST_S03_ICEFLUSH': 'Ice-Flush',
    'COOL_JUST_S01_ECOFLOW': 'Eco-Flow',
    'COOL_TYDT_S02_NIGHTFALL': 'NightFall',
    'COOL_TYDT_S02_HEATSINK': 'HeatSink',
    'COOL_TYDT_S01_HEATSAFE': 'HeatSafe',
    'COOL_TYDT_S01_SNOWBLIND': 'SnowBlind',
    'COOL_TYDT_S01_VAPORBLOCK': 'VaporBlock',
    'COOL_TYDT_S02_ICEBOX': 'IceBox',
    'COOL_ACOM_S01_ICEPLUNGE': 'IcePlunge',
    'COOL_ACOM_S01_QUICKCOOL': 'QuikCool',
    'COOL_ACOM_S02_ABSOLUTEZERO': 'AbsoluteZero',
    'COOL_ACOM_S02_RAPIDCOOL': 'RapidCool',
    'COOL_ACOM_S02_ICEDIVE': 'IceDive',
    'COOL_ACOM_S01_ZERORUSH': 'ZeroRush',
    'COOL_LPLT_S02_FULLFROST': 'FullFrost',
    'COOL_LPLT_S01_BLASTCHILL': 'BlastChill',
    'COOL_LPLT_S02_WHITEOUT': 'WhiteOut',
    'COOL_LPLT_S03_FROSTBITE': 'FrostBite',
    'COOL_LPLT_S03_COLDSURGE': 'ColdSurge',
    'COOL_LPLT_S01_FLASHFREEZE': 'FlashFreeze',
    'COOL_LPLT_S01_ARCTICSTORM': 'ArcticStorm',
    'COOL_LPLT_S03_FROSTBURN': 'FrostBurn',
    'COOL_LPLT_S02_COLDSNAP': 'ColdSnap',
    'COOL_RSI_S04_POLARIS': 'Serac',
    'COOL_ORIG_S04_890J': 'Serac',

    // Quantum Drives
    'QDRV_ACAS_S02_SUNFIRE': 'SunFire',
    'QDRV_ARCC_S01_FLOOD': 'Flood',
    'QDRV_ARCC_S01_RUSH': 'Rush',
    'QDRV_ARCC_S03_IMPULSE': 'Impulse',
    'QDRV_ARCC_S03_ECHO': 'Echo',
    'QDRV_JUST_S01_VULCAN': 'Vulcan',
    'QDRV_JUST_S02_HURACAN': 'Huracan',
    'QDRV_JUST_S01_COLOSSUS': 'Colossus',
    'QDRV_JUST_S01_GOLIATH': 'Goliath',
    'QDRV_JUST_S01_PONTIUS': 'Pontius',
    'QDRV_JUST_S03_REVENANT': 'Revenant',
    'QDRV_RACO_S02_NOVA': 'Nova',
    'QDRV_RACO_S01_SPECTRE': 'Spectre',
    'QDRV_RACO_S02_BOLT': 'Bolt',
    'QDRV_RACO_S01_SIREN': 'Siren',
    'QDRV_RSI_S01_ATLAS': 'Atlas',
    'QDRV_RSI_S01_EOS': 'Eos',
    'QDRV_RSI_S01_HYPERION': 'Hyperion',
    'QDRV_RSI_S03_EREBOS': 'Erebos',
    'QDRV_RSI_S02_KHAOS': 'Khaos',
    'QDRV_RSI_S03_METIS': 'Metis',
    'QDRV_RSI_S03_HEURA': 'Heura',
    'QDRV_TARS_S01_EXPEDITION': 'Expedition',
    'QDRV_TARS_S03_WANDERER': 'Wanderer',
    'QDRV_TARS_S03_RANGER': 'Ranger',
    'QDRV_TARS_S03_DRIFTER': 'Drifter',
    'QDRV_TARS_S01_VOYAGE': 'Voyage',
    'QDRV_TARS_S02_ODYSSEY': 'Odyssey',
    'QDRV_TARS_S01_BEACON': 'Beacon',
    'QDRV_WETK_S02_CROSSFIELD': 'Crossfield',
    'QDRV_WETK_S02_YEAGER': 'Yeager',
    'QDRV_WETK_S01_VK00': 'VK-00',
    'QDRV_WETK_S02_XL1': 'XL-1',
    'QDRV_WETK_S03_BALANDIN': 'Balandin',
    'QDRV_WETK_S03_PONTIAC': 'Pontiac',
    'QDRV_WETK_S02_HEURA': 'Heura',
    'QDRV_WETK_S02_AGNI': 'Agni',
    'QDRV_RSI_S04_POLARIS': 'Siren',
    'QDRV_ORIG_S04_890J': 'Siren',
    'QDRV_AEGS_S04_RECLAIMER': 'Siren',
    'QDRV_AEGS_S04_IDRIS': 'Siren'
};

const cleanName = (name, className) => {
    if (!name && !className) return 'Unknown Item';
    const raw = (name || '').trim();
    let clean = raw;
    if (raw.includes("'")) {
        const quoted = raw.match(/'([^']+)'/);
        if (quoted && quoted[1]) {
            const suffix = raw.split("'").pop()?.trim();
            if (suffix && (suffix.toLowerCase().includes('cannon') || suffix.toLowerCase().includes('repeater') || suffix.toLowerCase().includes('gatling') || suffix.toLowerCase().includes('scattergun'))) {
                clean = `${quoted[1]} ${suffix}`;
            } else {
                clean = quoted[1];
            }
        }
    }
    clean = clean.replace(/@[\w\s]*Name[ _]?|@LOC_PLACE_HOLDER_|@LOC_PLACEHOLDER_|@item_Name_|@LOC /gi, '').replace(/itemName/gi, '').replace(/Name([A-Z])/g, '$1').replace(/_/g, ' ').replace(/\(S\d+\)/gi, '').replace(/\sS\d+\s/gi, ' ').replace(/\sS\d+$/gi, '').replace(/\(.*\)/g, '').replace(/Laswer/gi, 'Laser').trim();

    if (className) {
        const normalized = className.toUpperCase().replace(/^NAME/i, '');
        if (WEAPON_NAME_MAP[normalized]) return WEAPON_NAME_MAP[normalized];
        if (COMPONENT_NAME_MAP[normalized]) return COMPONENT_NAME_MAP[normalized];
        const stripped = normalized.replace(/(_SCITEM|_TURRET|_LOWPOLY|_DUMMY|_VNG|_VANDUUL|_B_|_A_).*/gi, '');
        if (WEAPON_NAME_MAP[stripped]) return WEAPON_NAME_MAP[stripped];
        if (COMPONENT_NAME_MAP[stripped]) return COMPONENT_NAME_MAP[stripped];
        const sizeStripped = normalized.replace(/(_S\d+).*/gi, '$1');
        if (WEAPON_NAME_MAP[sizeStripped]) return WEAPON_NAME_MAP[sizeStripped];
        if (COMPONENT_NAME_MAP[sizeStripped]) return COMPONENT_NAME_MAP[sizeStripped];
    }
    return clean || className || 'Unknown Item';
};

const data = JSON.parse(fs.readFileSync('ship-items.json', 'utf8'));
const types = ['ShieldGenerator', 'Cooler', 'PowerPlant', 'QuantumDrive', 'WeaponGun'];

const results = data.filter(i => types.some(t => i.type && i.type.includes(t))).map(i => {
    const cleaned = cleanName(i.name, i.className);
    return {
        className: i.className,
        originalName: i.name,
        cleaned,
        type: i.type,
        messy: cleaned.includes('_') || cleaned.match(/S\d/) || cleaned === i.className || (i.name && i.name.includes('@LOC'))
    };
}).filter(r => r.messy && !r.originalName.includes('PLACEHOLDER') && r.cleaned !== 'CoolCore' && r.cleaned !== 'FullForce');

console.log(JSON.stringify(results.slice(0, 100), null, 2));
console.log(`Global Audit Failure Count: ${results.length}`);
